### ISSUE TITLE
Suggestion: Song Stats

### ISSUE THREAD

**Issue by ghost** [JBader89/PlugBot#2]
Suggestion:

Have the bot say in the chat-box, how many woots, mehs, and grabs, the song got while it was playing.

**Comment by JBader89** [comment]
I have a few other pertinent commands in my queue that I'd like to implement first, but I will look into making a song stats command soon. The reason it wasn't at the top of my list was that the room I usually hang out in (Chillout Mixer, Ambient + Triphop) has another bot which handles all of the room stats, with a running database of all the music that's ever been played in the room. The database is even carried over from Turntable.fm, believe it or not, so it's been running for over two years. Anyway, I will get back to you on this when I've finished up with some of the other commands on my list.

**Comment by ghost** [comment]
I saw that you added Song Stats. :)

**Comment by JBader89** [comment]
Finally! Haha sorry it took me so long, turns out it was easier to do than I thought ;)
