### ISSUE TITLE
Grab Command Bug

### ISSUE THREAD

**Issue by ghost** [JBader89/PlugBot#7]
Whenever anybody types in .grab in the chat box, while using my bot, the bot doesn't grab the song, and the grab counter on PlugDJ doesn't go up. 

The Bug Occured: March 6, 2014
Room: http://plug.dj/christian-anything-2/
Bot: Mega-Bot

**Comment by JBader89** [comment]
that's because you wrote "if (data.from=='christian-anything-2')" - not sure why you did that. that will only trigger the command when a _user_ named 'christian-anything-2' writes .grab in the chat box.

**Comment by JBader89** [comment]
if you want anyone to be able to use it, you need to take that line out completely
